site_name: In-Betweens
repo_url: https://github.com/jamesvsnowden/bl_in_betweens
repo_name: Github
site_description: In-Between shape keys for Blender
site_author: James Snowden
copyright: Copyright &copy; 2022 James V Snowden
nav:
  - Home: 'index.md'
  - 'Docs':
    - Installation:  'user-guide/installation.md'
    - 'Quick Start': 'user-guide/getting-started.md'
    - 'Workflow': 'user-guide/workflow.md'
    - 'Settings': 'user-guide/inbetween-settings.md'
    - 'Updating': 'user-guide/updating.md'
  - Support: 'support.md'
  - Purchase: 'buy.md'
  # - Releases: 'releases.md'
theme:
  name: material
  custom_dir: overrides
  logo: /img/logo_pro.svg
  palette:
    primary: orange
    accent: orange
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  language: en
plugins:
  - search
markdown_extensions:
  - meta
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.keys
extra:
  homepage: "/"
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jamesvsnowden
      name: James V Snowden on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/jamesvsnowden
      name: James V Snowden on Github
extra_css:
  - stylesheets/extra.css